# GitHub Actions workflow for building the s2geometry library

on:
  workflow_call:

jobs:
  s2geometry:
    name: Build s2geometry library for CATCH testing
    runs-on: ubuntu-latest
    steps:
      - name: Check for cached files
        uses: actions/cache/restore@v4
        id: cache
        with:
          key: s2geometry-py311
          path: |
            /usr/local/include/s2
            /usr/local/lib/libs2.so*
      - name: Checkout build script
        uses: actions/checkout@v4
      - name: Set up Python
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build and install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          ls
          cp $GITHUB_WORKSPACE/_install_s2 .
          S2PREFIX=/usr/local bash _install_s2
      # - name: Cache data
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   uses: actions/cache/save@v4
      #   with:
      #     key: s2geometry-py311
      #     path: |
      #       .venv/include/s2
      #       .venv/lib/libs2.so*
