# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

# Remove -numpy126 when we support testing with numpy 2.0

name: CI Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    # branches: # only build on PRs against 'main' if you need to further limit when CI is run.
    #    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ARCH_ON_CI: "normal"
  IS_CRON: "false"
  PYTHON_VERSION: "3.11"

jobs:
  s2geometry:
    uses: ./.github/workflows/build-s2geometry.yml
  test:
    name: CI testing
    needs: [s2geometry]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Restore virtual environment from cache
        uses: actions/cache/restore@v4
        id: cache
        with:
          key: s2geometry-py${{ steps.setup-python.outputs.python-version }}
          path: |
            ${HOME}/.venv
      - name: Activate venv
        run: |
          source ${HOME}/.venv/bin/activate
